server:
  port: 9000

spring:
  cloud:
    config:
      server:
        git:
          uri: D:\Projects\code-examples\my-projects\git-repository-spring-cloud-camel
  application:
    name: config-server

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

